const CHANGE_VIEW = "CHANGE_VIEW";

const LOAD_ITEMS = "LOAD_ITEMS";
const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
const LOAD_ITEMS_FAIL = "LOAD_ITEMS_FAIL";

export default {
    CHANGE_VIEW,
    LOAD_ITEMS,
    LOAD_ITEMS_SUCCESS,
    LOAD_ITEMS_FAIL
};