const CHANGE_VIEW = "CHANGE_VIEW";

const LOAD_ENTRIES = "LOAD_ENTRIES";
const LOAD_ENTRIES_SUCCESS = "LOAD_ENTRIES_SUCCESS";
const LOAD_ENTRIES_FAIL = "LOAD_ENTRIES_FAIL";

export default {
    CHANGE_VIEW,
    LOAD_ENTRIES,
    LOAD_ENTRIES_SUCCESS,
    LOAD_ENTRIES_FAIL
};